DigicelApps/Controllers/ApplicationController.cs
using DigicelApps.Models;
using DigicelApps.Models.DTOs;
using DigicelApps.Services;
using DigicelApps.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DigicelApps.Controllers
{

    public class ApplicationController : Controller
    {

        private IApplication _app;

        private ICategory _category;

        public ApplicationController(IApplication app, ICategory category)
        {
            _app = app;
            _category = category;
        }


        [HttpGet]
        public async Task<IActionResult>  CreateApp()
        {
            ViewBag.categories =await _category.Categories();
            return View("Index");
        }


        [HttpGet]
        public  IActionResult Menu()
        {
           
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ViewApps()
        {
           var apps = await _app.getAll();
            return View(apps);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.categories = await _category.Categories();
            var app = await _app.GetById(id);
            return View(app);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Application app)
        {
            if (ModelState.IsValid)
            {
                if (await _app.Update(app))
                {
                    ViewBag.success = "La aplicación fue Editada Exitosamente";
                    return View("ViewApps",await _app.getAll());
                }
                else
                {
                    ViewBag.error = "La applicación no pudo ser editada intente nuevamente";
                    return View("ViewApps",await _app.getAll());
                }
            }
            else
            {
                ViewBag.categories = await _category.Categories();
                return View("Edit", app);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            ViewBag.categories = await _category.Categories();
            var app = await _app.GetById(id);
            return View(app);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Application app)
        {
                if (await _app.Delete(app.Id))
                {
                    ViewBag.success = "La aplicación fue Eliminada Exitosamente";
                    return View("ViewApps", await _app.getAll());
                }
                else
                {
                    ViewBag.error = "La applicación no puedo ser eliminada nuevamente";
                    return View("ViewApps", await _app.getAll());
                }
            }
          
        



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateApp(ApplicationCreationDto app)
        {
            if (ModelState.IsValid)
            {
                if (await _app.Create(app))
                {
                    ViewBag.success = "La aplicación fue creada Exitosamente";
                    return View("ViewApps",await _app.getAll());
                }
                else
                {
                    ViewBag.error = "La applicación no puedo ser creada intente nuevamente";
                    return  View("Index",app);
                }              
            }
            else
            {
                ViewBag.categories = await _category.Categories();
                return View("Index", app);
            }                        
        }



    }
}

DigicelApps/Controllers/CategoryController.cs
using DigicelApps.Models;
using DigicelApps.Models.DTOs;
using DigicelApps.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DigicelApps.Controllers
{
    public class CategoryController : Controller
    {
        private ICategory _cat;
        public CategoryController(ICategory cat)
        {
            _cat = cat;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult>  CategoryList()
        {
            
            return View(await _cat.Categories());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryCreationDto category)
        {

            if (ModelState.IsValid)
            {
                if (await _cat.Create(category))
                {
                    ViewBag.success = "La Categoria fue creada Exitosamente";
                    return View("CategoryList", await _cat.Categories());
                }
                else
                {
                    ViewBag.error = "La applicación no puedo ser creada intente nuevamente";
                    return View("Index", category);
                }
            }
            else
            {                
                return View("Index", category);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            return View(await _cat.GetById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Category category)
        {

            if (ModelState.IsValid)
            {
                if (await _cat.Update(category))
                {
                    ViewBag.success = "La Categoria fue editada Exitosamente";
                    return View("CategoryList", await _cat.Categories());
                }
                else
                {
                    ViewBag.error = "La Categoria no puedo ser editada intente nuevamente";
                    return View("Index", category);
                }
            }
            else
            {
                return View("Index", category);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            return View(await _cat.GetById(id));
        }


        [HttpPost]
        public async Task<IActionResult> Delete(Category category)
        {

            if (ModelState.IsValid)
            {
                if (await _cat.DeleteCategoriesAndApplications(category.Id))
                {
                    ViewBag.success = "La Categoria y sus aplicaciones fueron eliminada Exitosamente";
                    return View("CategoryList", await _cat.Categories());
                }
                else
                {
                    ViewBag.error = "La Categoria no pudo ser editada intente nuevamente";
                    return View("Index", category);
                }
            }
            else
            {
                return View("Index", category);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Top5()
        {
            return View(await _cat.GetTop5());
        }

    }
}

DigicelApps/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DigicelApps</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />   
    <link href="~/lib/datatable/css/datatable-bootstrap.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" asp-action="Index" asp-controller="Home">Digicel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-action="Menu" asp-controller="Application">Aplicaciones <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Category">Categorias</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Acciones
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Ver top 5</a>
                            <a class="dropdown-item" href="#">Apps por categoria</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Otros</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Iniciar Session</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color:black; color:white" class="border-top footer text-muted">
        <div style="color:white" class="container">
            &copy; 2021 - Digicel  - Derechos Reservados © 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>   
    <script src="~/lib/datatables.net/jquery.dataTables.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>